global:
  scrape_interval: 15s

  external_labels:
    monitor: 'metric-monitor'

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    scheme: http
